#-------------------------------
# General Site Settings

title: DemonWolfDev
name: MrDemonWolf
description: Are you passionate about tech, computers, creativity, and gaming? Grow with our community towards your goals. Join us today!
email: webmaster@demonwolfdev.com
url: https://www.demonwolfdev.com
#url: http://localhost:3000  #Dev URL

#-------------------------------
# Menu Items
menu: 
  #- {title: Forums, url: 'forums'}
  - {title: Discord, url: 'https://discordapp.com/invite/A9x3qEN'}
  #- {title: Donate, url: 'https://www.donorbox.org/demonwolfdev'}

#-------------------------------

# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/demonwolfdev'
  type: 'website'

#-------------------------------
# Google Analytics Section

google-analytics-ua: UA-xxxx-xx

#-------------------------------
# About Section

about:
  header: About Us
  text: "DemonWolfDev is an open community that provides friendly, socially rewarding gaming and creative experiences. Our creative nature stimulates a friendly environment where sharing and collaborating on projects is welcomed whilst maintaining a place for people that prefer to work solo and are simply seeking advice.  It's hard to have a fun and rewarding online experience when gaming online. Trolls and jerks are everywhere. DemonWolfDev offers an antidote. You’ll find our community active and friendly. Our team of volunteer admins actively keeps the jerks, trolls, and cheaters out.  Best of all, DemonWolfDev is open to everyone — there are no applications, prerequisites, or approval processes. You’re a member of the DemonWolfDev community from the moment you start creating or gaming with us. Are you passionate about tech, computers, creativity, and gaming? Grow with our community towards your goals."

#-------------------------------
# Hero Section

hero:
    header: 'DemonWolfDev Community'
    text: "Are you passionate about tech, computers, creativity, and gaming? Grow with our community towards your goals. Join us today!"
    buttom-text: Join Us!
    button-link: '#learn'
#-------------------------------
# CTA Section

cta:
  header: Join Our Community Today!
  text: Its free!
  button-text: Join Us!
  #button-url: '#join'
  button-url: 'https://discordapp.com/invite/A9x3qEN'
#-------------------------------
# Ofter Section

ofter: 
  - {icon: fa-list-alt, name: 'Voice Chat & Private Messages', description: 'Our Discord has members from all ages, gaming backgrounds, people who use different gaming systems, and much more.'}
  # {icon: fa-comments-o, name: 'Discord Channels & Forums Threads', description: ' We have a voice and private messages so you can chat with other members. You can also use it for in game voice chat, or just for having fun.  Even just hangout with members.'}
  - {icon: fa-comments-o, name: 'Discord Text & Voice Channels', description: ' We have a voice and private messages so you can chat with other members. You can also use it for in game voice chat, or just for having fun.  Even just hangout with members.'}

#-------------------------------
# Social Links/Icons

social: 
  - {icon: fa-twitch, color: 'twitch-color', url: '#'}
  - {icon: fa-youtube-play, color: 'youtube-color', url: '#'}
  - {icon: fa-google-plus, color: 'google_plus-color', url: '#'}
  - {icon: fa-twitter, color: 'twitter-color', url: '#'}

#-------------------------------
# Modified Date

modified-date: September 25, 2017
#-------------------------------
