#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
  - {title: Discord, url: 'https://discordapp.com/invite/A9x3qEN'}
  - {title: Donate, url: 'https://streamlabs.com/demonwolfdev'}

#-------------------------------

# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/demonwolfdev'
  type: 'website'
  google-analytics: UA-104966812-1
  url: 'https://www.demonwolfdev.com'

#-------------------------------
# About Section

about:
  header: About Us
  text:
    - "DemonWolfDev is an open community that provides friendly, socially rewarding gaming and creative experiences. Our creative nature stimulates a friendly environment where sharing and collaborating on projects is welcomed whilst maintaining a place for people that prefer to work solo and are simply seeking advice."
    - "It's hard to have a fun and rewarding online experience when gaming online. Trolls and jerks are everywhere. DemonWolfDev offers an antidote. You’ll find our community active and friendly. Our team of volunteer admins actively keeps the jerks, trolls, and cheaters out."
    - "Best of all, DemonWolfDev is open to everyone — there are no applications, prerequisites, or approval processes. You’re a member of the DemonWolfDev community from the moment you start creating or gaming with us. Are you passionate about tech, computers, creativity, and gaming? Grow with our community towards your goals."

#-------------------------------
# Hero Section

hero:
  header: 'DemonWolfDev Community'
  text: "Are you passionate about tech, computers, creativity, and gaming? Grow with our community towards your goals. Join us today!"
hero-button:
  title: Learn More
  url: '#about'

#-------------------------------
# CTA Section

cta:
  header: Join Our Community Today!
  text: Its free!

cta-button:
  title: Join Us!
  url: 'https://discordapp.com/invite/A9x3qEN'

#-------------------------------
# Ofter Section

ofter:
  - {icon: fa-list-alt, name: 'Discord Voice Chat & Private Messages', description: 'On our discord server you can chat with members from all ages, gaming backgrounds, people who use different gaming systems, and much more.'}
  - {icon: fa-comments-o, name: 'Discord Text Channels' , description: 'In the community text channels you are able to make posts with other members.  Learn more about members and they can learn about you.'}

#-------------------------------
# Social Icons and URls

social:
  - {icon: fab fa-twitch, color: 'twitch-color twitch-color_border', url: 'https://www.twitch.tv/demonwolfdev'}
  - {icon: fab fa-youtube, color: 'youtube-color youtube-color_border', url: 'https://www.yotube.com/DemonWolfDevOfficial'}
  - {icon: fab fa-google-plus-g, color: 'google_plus-color google_plus-color_border', url: 'http://plus.google.com/+DemonWolfDevOfficial'}
  - {icon: fab fa-twitter, color: 'twitter-color twitter-color_border', url: 'https://www.twitter.com/demonwolfdev'}

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
